package com.climate.decode.eventservice.converter.refrigerantnondrinkablewater;

import com.climate.decode.eventservice.converter.Converter;
import com.climate.decode.eventservice.dto.refrigerantnondrinkablewater.RefrigerantNonDrinkableWaterDetailsDto;
import com.climate.decode.eventservice.entity.refrigerantnondrinkablewater.RefrigerantNonDrinkableWaterDetails;

public interface RefrigerantNonDrinkableWaterDetailsConverter extends Converter<RefrigerantNonDrinkableWaterDetails, RefrigerantNonDrinkableWaterDetailsDto> {

}
